"""add kalshi tables

Revision ID: 8d5640415024
Revises: 20260326_000005
Create Date: 2026-03-31 18:05:37.146772
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '8d5640415024'
down_revision = '20260326_000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
